### ISSUE TITLE
How we can use fastapi-users-db-sqlmodel 

### ISSUE THREAD

**Issue by AdamMusa** [fastapi-users/fastapi-users-db-sqlmodel#2]
I don't know exactly how to use this library . It's didn't have an example otherwise it would be cool

**Comment by paolodina** [comment]
@frankie567 
Hello! Now that https://github.com/tiangolo/sqlmodel/pull/26 has landed (IIRC that was problematic for FastAPI users with SQLModel), any chance for help on this? Maybe a code example or some tip...? Thanks
